{% set name = "specutils" %}
{% set version = "0.4b2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "93da8c758c31db666686c8c29ce9b27bd35d58393bb7950330fc9ca5cd0ced4c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - astropy
    - six
    - gwcs
    - scipy
  run:
    - python
    - astropy
    - six
    - gwcs
    - scipy

test:
  imports:
    - specutils
    - specutils.analysis
    - specutils.fitting
    - specutils.io
    - specutils.io.default_loaders
    - specutils.manipulation
    - specutils.spectra
    - specutils.tests
    - specutils.utils
    - specutils.wcs
    - specutils.wcs.adapters

about:
  home: http://specutils.readthedocs.io/
  license: BSD
  license_family: BSD
  license_file: ''
  summary: Astropy affiliated package for astronomical spectral operations.
  description: "The specutils package implements base classes and utilities for\r\ninteracting with astronomical spectra in Python and the Astropy\r\nproject.  It is intended for eventual merger with the\
    \ `astropy`\r\npackage, but for now is being developed independently."
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
