{% set python_min = "3.10" %}
{% set name = "specutils" %}
{% set version = "1.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51ee9d17e56d24e33c23e44c18be704a7621c80f544e208e63c9de6e75bacbeb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - setuptools
  run:
    - numpy >=1.24
    - scipy >=1.3
    - python >={{ python_min }}
    - astropy-base >=5.1
    - gwcs >=0.18
    - asdf-astropy >=0.3
    - asdf >=2.14.4
    - ndcube >=2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - specutils
    - specutils.analysis
    - specutils.fitting
    - specutils.io
    - specutils.io.default_loaders
    - specutils.manipulation
    - specutils.spectra
    - specutils.utils

about:
  home: http://specutils.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Astropy affiliated package for astronomical spectral operations.
  description: |
    The specutils package implements base classes and utilities for
    interacting with astronomical spectra in Python and the Astropy project.
    It is intended for eventual merger with the `astropy` package, but for now
    is being developed independently.
  doc_url: http://specutils.readthedocs.io/
  dev_url: https://github.com/astropy/specutils

extra:
  recipe-maintainers:
    - rosteen
    - mwcraig
    - bsipocz
    - nmearl
    - crawfordsm
    - keflavich
    - eteq
