{% set name = "specutils" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8cde472d25018f0e2fe01a22a5a25678bb921627e6a4b5ed1c41f2dd77d7391c
  patches:
    - setup.cfg.patch

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3
    - pip
    - astropy >=4
    - astropy-helpers >=4
    - gwcs >=0.12
    - scipy
    - wget
  run:
    - python >=3
    - astropy >=4
    - gwcs >=0.12
    - asdf >=2.5
    - scipy

test:
  imports:
    - specutils
    - specutils.analysis
    - specutils.fitting
    - specutils.io
    - specutils.io.default_loaders
    - specutils.manipulation
    - specutils.spectra
    - specutils.utils

about:
  home: http://specutils.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Astropy affiliated package for astronomical spectral operations.
  description: "The specutils package implements base classes and utilities for\r\ninteracting with astronomical spectra in Python and the Astropy\r\nproject.  It is intended for eventual merger with the `astropy`\r\npackage, but for now is being developed independently."
  doc_url: http://specutils.readthedocs.io/
  dev_url: https://github.com/astropy/specutils

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - nmearl
    - crawfordsm
    - keflavich
    - eteq
