{% set name = "specutils" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e383669fb94e26a5a3e98c581c093014745b6f1e0d56c67d7f17317f177061af

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - numpy >=1.19
    - scipy >=1.3
    - python >=3.8
    - astropy >=5.1
    - gwcs >=0.18
    - asdf-astropy >=0.3
    - asdf >=2.5
    - ndcube >=2.0

test:
  imports:
    - specutils
    - specutils.analysis
    - specutils.fitting
    - specutils.io
    - specutils.io.default_loaders
    - specutils.manipulation
    - specutils.spectra
    - specutils.utils

about:
  home: http://specutils.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Astropy affiliated package for astronomical spectral operations.
  description: |
    The specutils package implements base classes and utilities for
    interacting with astronomical spectra in Python and the Astropy project.
    It is intended for eventual merger with the `astropy` package, but for now
    is being developed independently.
  doc_url: http://specutils.readthedocs.io/
  dev_url: https://github.com/astropy/specutils

extra:
  recipe-maintainers:
    - rosteen
    - mwcraig
    - bsipocz
    - nmearl
    - crawfordsm
    - keflavich
    - eteq
