travis:
  secure:
    BINSTAR_TOKEN: OcQXmdcUEBeZjkujR1IvkX/sZ2RDOq7yiIsOVP5pK8UzLVKit7sxg4a135uNBUo5DqgyTb9qB0UgmIehlIHoPr6A0CTNJTvKsLZAFaDeloFa786Sm0G40McoMYG/ywpgelJly/fbzCDRMx4wbhF4YLpICcTQYdyNfyexLfaDS7f1iw86yMonC0Kk/V5Nha2plzrixEHnzzq5VFiaYpdQuV1lrChB2lYs+GpLLTxVU8cAV4fiSeabTDmbBIN6hIv1RLIhDg5rBtGUbKfAhMqvXtdfBf4ONmyQ60XEfytgZ+zU8HOC8gCYr98EKo4aahqbqVIBn7QDT3OSV86kWCLM0FPWa0YfXsx0Np/u8AeO8QOeQrZfXWvdMcHC4WSuZ1yJCWLygCUEa2wIudRLLfelhT0s2S74km5kYx2jSdGNqSiiwrpTHSMFjo9WWyx7f4+PXx4LaaKjzKvpYC+sW6xBcdz0oc+2MwvCujM8KilvP4C2avYcE2WvI3bY/nbTJ6OiI55m1FOzxREd5twiBnZVwjJ8gNYfu7kQHImji+0LMIgtih/1Kxt/h5ocY6zsGPcFzrppJX6g06iLypGLW2Wsk0bnNnygMTjb+I9b/VIF7qCGn9+cblH3+kiAcC+8POEvDAJ3kwJeJpvo8cjU5xnE0ZMF64qst9b8sI9CRboBjY0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
